// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANL-PHxnlVAKlBJqOuLuZ3UoSauRwpf7U',
    appId: '1:444330182387:web:e3fb27b8de7096a3da1986',
    messagingSenderId: '444330182387',
    projectId: 'kranthigadiproject',
    authDomain: 'kranthigadiproject.firebaseapp.com',
    storageBucket: 'kranthigadiproject.firebasestorage.app',
    measurementId: 'G-LH1ZKGN6LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZItar8UVGYoBwId4x7KVAWJwg8ffeH8',
    appId: '1:444330182387:android:8a5d279d84938182da1986',
    messagingSenderId: '444330182387',
    projectId: 'kranthigadiproject',
    storageBucket: 'kranthigadiproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWbnFXWZ5cHca54BYo_KghPHXOKNDKSg',
    appId: '1:444330182387:ios:bfe423440dd54659da1986',
    messagingSenderId: '444330182387',
    projectId: 'kranthigadiproject',
    storageBucket: 'kranthigadiproject.firebasestorage.app',
    iosBundleId: 'com.example.weektasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWbnFXWZ5cHca54BYo_KghPHXOKNDKSg',
    appId: '1:444330182387:ios:bfe423440dd54659da1986',
    messagingSenderId: '444330182387',
    projectId: 'kranthigadiproject',
    storageBucket: 'kranthigadiproject.firebasestorage.app',
    iosBundleId: 'com.example.weektasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANL-PHxnlVAKlBJqOuLuZ3UoSauRwpf7U',
    appId: '1:444330182387:web:ec7b04a1e4217ad0da1986',
    messagingSenderId: '444330182387',
    projectId: 'kranthigadiproject',
    authDomain: 'kranthigadiproject.firebaseapp.com',
    storageBucket: 'kranthigadiproject.firebasestorage.app',
    measurementId: 'G-8C9MHLZRCP',
  );
}
